### PR TITLE
Github actions for more connectivity!

### LINKED ISSUE #79: Github actions for more connectivity!
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Rakshit-gen 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

### PR DESCRIPTION
**Pull request by smog-root**
Closes #79 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Rakshit-gen 

_**Note**_: Add all the labels and assign me to this PR !!

### CODE REVIEW

**Comment by smog-root** [comment]
**Proof**:

**Issue open and close:**

Screenshot 2024-10-21 152058
<br>

**PR raise and  merged:**
Screenshot 2024-10-21 160211

**Comment by Rakshit-gen** [comment]
I see it is working @smog-root 
Thanks for the contribution

**Comment by smog-root** [comment]
@Rakshit-gen hey.. have done another issue too in this PR!! #76. So add level3 to this PR!

**Comment by Rakshit-gen** [comment]
Ohh then I can add level.3 @smog-root 
Wait

**Comment by Rakshit-gen** [comment]
Added

**Review by MastanSayyad — COMMENTED** [review]
as this PR has 3 workflows it can only have level 2  @Rakshit-gen 

image

**Pull request merged**
