### PR TITLE
Improve the UI of Dashboard page

### PR DESCRIPTION
**Pull request by vidhvath28**
###  Description:  

_This PR improves the overall user experience by styling and subtle animations to the Dashboard Section. The changes aim to create a modern and dynamic interface, aligning with Web3 design aesthetics._ 

#### Key Changes:

- Added futuristic gradients, neon glows, and glassmorphism effects to the template cards.
- Implemented smooth animations for hover and card interactions, improving the look and feel.
- Updated layout responsiveness across different screen sizes (mobile, tablet, desktop).
- Ensured performance optimization while incorporating animations to avoid lags.

_These enhancements elevate the visual appeal of the platform, providing a cutting-edge experience for users browsing through templates._

### CODE REVIEW

**Comment by Rakshit-gen** [comment]
Merged @vidhvath28

**Comment by Rakshit-gen** [comment]
There are some issues with your pr kindly check for those, try deploying it by yourself and send a new PR

**Comment by vidhvath28** [comment]
Ya sure, I am really sorry for those issues.

**Comment by Rakshit-gen** [comment]
Kindly solve those issues @vidhvath28

**Pull request merged**
