### PR TITLE
added history-page

### PR DESCRIPTION
**Pull request by Swetabh333**
Added the history page using shadcn cards and dialogs
<br/>
Screenshot from 2024-10-04 00-43-20
<br/>
To keep all the card sizes uniform I added a button to view the full content
<br/>
Screenshot from 2024-10-04 00-43-28
<br/>
Made sure it looks fine in light mode
<br/>
Screenshot from 2024-10-04 00-43-37
<br/>
Screenshot from 2024-10-04 00-43-43
<br/>
Made sure it is responsive as well
<br/>
Screenshot from 2024-10-04 00-44-14
<br/>
Screenshot from 2024-10-04 00-44-19

### CODE REVIEW

**Comment by Rakshit-gen** [comment]
Merged @Swetabh333 Thanks alot for the contribution!

**Comment by Swetabh333** [comment]
Thanks @Rakshit-gen it was fun

Also I remembered I haven't added any button to actually navigate to the history page.Should I create another issue for it?

**Comment by Rakshit-gen** [comment]
I actually added one as I noticed it while testing the website @Swetabh333

**Comment by Swetabh333** [comment]
ok great

it was nice working with you @Rakshit-gen

**Comment by Rakshit-gen** [comment]
Thanks @Swetabh333 it was great working with you too!
Do find more issues to work on as you go
Best of luck

**Comment by Rakshit-gen** [comment]
Hey @Swetabh333 can this type of issue be fixed?

image

**Comment by Swetabh333** [comment]
@Rakshit-gen I think it can be fixed with making with making it scrollable even in x-direction

**Comment by Swetabh333** [comment]
@Rakshit-gen I think it can be fixed with making with making it scrollable even in x-direction

**Comment by Rakshit-gen** [comment]
You can open a new issue and fix it, I will assign it to you and it can be of level 2 @Swetabh333

**Comment by Swetabh333** [comment]
@Rakshit-gen Is it alright if I do it in the morning?

**Comment by Rakshit-gen** [comment]
Sure anytime @Swetabh333

**Comment by Swetabh333** [comment]
@Rakshit-gen  can you tell me which prompt you used to get that python code so I can replicate the errror?

**Comment by Rakshit-gen** [comment]
In generate-code it is happening for all the prompts @Swetabh333

**Pull request merged**
