### PR TITLE
added history-page

### PR DESCRIPTION
**Pull request by Swetabh333**
Added the history page using shard cn cards and dialogs
<br/>
Screenshot from 2024-10-04 00-43-20
<br/>
The cards are all of similar length.To read the full response you can click on the view full content button
<br/>
Screenshot from 2024-10-04 00-43-28
<br/>
made sure it looks fine in light mode as well
<br/>
Screenshot from 2024-10-04 00-43-37
<br/>
Screenshot from 2024-10-04 00-43-43
<br/>
made sure to keep it responsive as well
<br/>
Screenshot from 2024-10-04 00-44-14
<br/>
Screenshot from 2024-10-04 00-44-19

### CODE REVIEW

**Comment by Rakshit-gen** [comment]
Looks amazing @Swetabh333 , Thanks alot for the contribution!

**Comment by Rakshit-gen** [comment]
Why did you close the PR @Swetabh333

**Comment by Swetabh333** [comment]
I put the env variables in .env instead - of .env.local and it got pushed , I'll fix it and raise a new one in just a min

**Comment by Rakshit-gen** [comment]
Okay @Swetabh333 got it

**Pull request closed without merging**
