### PR TITLE
#34 fixed unnecessary home page access while user is logged in.

### PR DESCRIPTION
**Pull request by PrayanshParmar**

### CODE REVIEW

**Comment by Rakshit-gen** [comment]
@PrayanshParmar Since this PR was merged, a logged in user can't visit back to the home page at all, kindly fix that!
Make a new issue and do that

**Comment by Rakshit-gen** [comment]
Make it so that user is redirected to dashboard after login,
but can access the homepage afterward when he wants

**Comment by PrayanshParmar** [comment]
@Rakshit-gen  That's the feature I have suggested to you that if a user is logged in he does not need to go to home page, dashboard and profile page is enough, and you have approved it, now again you are telling to revert it.

**Comment by Rakshit-gen** [comment]
Okay but then what's the role of home button on the sidenav of the dahsboard?

**Comment by PrayanshParmar** [comment]
Repalce it with profile page

**Comment by Rakshit-gen** [comment]
Done

**Pull request merged**
