### PR TITLE
changes made in navbar

### LINKED ISSUE #1: Improve navbar design
It is a simple gradient right now change it to something suiting to the theme

### PR DESCRIPTION
**Pull request by Sourabh782**
Made some changes in navbar

Closes #1 

There was no proper spacing in navbar

1. Signin get out of navbar when on lower width device:
Screenshot 2024-10-03 190053

changes: 
Screenshot 2024-10-03 184035
Screenshot 2024-10-03 184029

### CODE REVIEW

**Comment by Sourabh782** [comment]
@Rakshit-gen can u add tags also 
And also mention if u have some other tasks

**Comment by Rakshit-gen** [comment]
@Sourabh782 done

**Comment by Rakshit-gen** [comment]
@Sourabh782  Pick any unassigned issue preferably logo designing if you are comfortable.

**Comment by Rakshit-gen** [comment]
@Sourabh782 Thanks for the contribution, kindly star the repo if you like the project!

**Comment by Sourabh782** [comment]
@Rakshit-gen

**Pull request merged**
